spring:
  profiles:
    active: dev

---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: cloud-config-client
eureka:
  client:
    service-url: 
      defaultZone: http://eureka-server1:7001/eureka/
---
server:
  port: 8202
spring:
  profiles: prod
  application:
    name: cloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:7001/eureka/