eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: gateway.com
    prefer-ip-address: true

spring:
  application:
    name: gateway

server:
  port: 9527

zuul:
  #封口 禁止直接通过provider来访问
  ignored-services: provider
  routes:
   myservice.serviceId: PROVIDER
   myservice.path: /service/**
  #前缀名
  prefix: /hcloud

