server:
  port: 7001
eureka:
  instance:
    hostname: eureka-server1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server2:7002/eureka/,http://eureka-server3:7003/eureka/