server:
  port: 7003
eureka:
  instance:
    hostname: eureka-server3
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:  #集群配置
      defaultZone: http://eureka-server1:7001/eureka/,http://eureka-server2:7002/eureka/